### ISSUE TITLE
Heads-up: Satisfactory doesn't use the STEAM query protocol

### ISSUE THREAD

**Issue by Kadigan** [AunePVP/Game-Server-Query-and-Control-Center#3]
Just wanted to let you know. They're using their own protocols - one Query, where you can get server version and Beacon port number, and the encrypted DTLS Beacon protocol, which is currently unknown.

EDIT:
I did _not_ add the "Server request" label. ;]

EDIT 2:
Ah yes, I missed the "blank issue" option. Apologies.

**Comment by AunePVP** [comment]
Thank you for letting me know.
